name: main

on:
  push:
    branches:
      - main
    # Only run when there are dotnet changes
    paths:
      - DotNetLlama/**
      - DotNetLlama.Test/**
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    uses: mattncott/mattncott-common/.github/workflows/test-dotnet.yml@main
    secrets: inherit

  release:
    name: Release
    uses: mattncott/mattncott-common/.github/workflows/release-to-nuget.yml@main
    secrets: inherit
    with:
      csproj-location: DotNetLlama/DotNetLlama.csproj
    needs: [ test ]

  version:
    name: Increase Version
    uses: mattncott/mattncott-common/.github/workflows/increase-dotnet-version.yml@main
    secrets: inherit
    with:
      csproj-location: DotNetLlama/DotNetLlama.csproj
    needs: [ release ]